version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
    working_dir: /app
    command: flask run -h 0.0.0.0 -p 5000
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
    depends_on:
      - db
      - redis

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile.postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6381:6379'

volumes:
  pgdata: